'use client';

import { Phone, UserRound, Wrench } from 'lucide-react';

import { Modal } from '@/components/common/modal';
import { useLanguage } from '@/lib/i18n/language-provider';
import type { DashboardEmployee, DashboardService } from '@/types/dashboard';

export function EmployeeDetailsModal({ employee, services, onClose }: { employee: DashboardEmployee | null; services: DashboardService[]; onClose: () => void }) {
  const { locale, copy } = useLanguage();
  return <Modal isOpen={Boolean(employee)} label={copy.dashboard.staffDetails} closeLabel={copy.dashboard.close} onClose={onClose}>{employee && <section className="p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="inline-flex size-12 items-center justify-center rounded-2xl bg-[var(--soft-violet)] text-[var(--brand)]"><UserRound size={23} aria-hidden="true" /></span><div><p className="text-sm font-bold text-[var(--brand)]">{copy.dashboard.staffDetails}</p><h2 className="mt-1 text-2xl font-black tracking-tight">{employee.name[locale]}</h2><p className="mt-1 text-sm font-bold text-[var(--muted)]">{employee.position[locale]}</p></div></div><span className={`rounded-full px-3 py-1 text-xs font-black ${employee.status === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{employee.status === 'active' ? copy.dashboard.active : copy.dashboard.inactive}</span></div><div className="mt-6 rounded-2xl border border-[var(--line)] bg-[#faf9ff] p-4 text-sm font-semibold text-[#536383]"><span className="inline-flex items-center gap-2"><Phone size={16} className="text-[var(--brand)]" aria-hidden="true" />{copy.dashboard.contactLabel}: {employee.contactLabel}</span></div><section className="mt-6"><div className="flex items-center gap-2"><Wrench size={17} className="text-[var(--brand)]" aria-hidden="true" /><h3 className="text-lg font-black">{copy.dashboard.assignedServices}</h3></div><div className="mt-3 grid gap-3">{services.length ? services.map((service) => <article key={service.id} className="rounded-2xl border border-[var(--line)] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-black">{service.name[locale]}</h4><p className="mt-1 text-sm text-[var(--muted)]">{service.description[locale]}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${service.status === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{service.status === 'active' ? copy.dashboard.active : copy.dashboard.inactive}</span></div><p className="mt-3 text-sm font-bold text-[var(--brand)]">{copy.businessProfile.price}{service.price} · {service.durationMinutes} {copy.businessProfile.duration}</p></article>) : <p className="text-sm text-[var(--muted)]">—</p>}</div></section></section>}</Modal>;
}
