#!/usr/bin/env bash
# Regenerate .env.test.local from the running local Supabase stack.
#
# The keys the CLI prints are the same well-known development keys on every
# machine and are not secret; the file is gitignored anyway so that nobody's
# cloud credentials can reach the integration suite by accident.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! supabase status >/dev/null 2>&1; then
  echo "The local Supabase stack is not running. Start it with: supabase start" >&2
  exit 1
fi

status_json="$(supabase status -o json)"
read_key() { node -e "process.stdout.write(JSON.parse(process.argv[1])[process.argv[2]] ?? '')" "$status_json" "$1"; }

cat > .env.test.local <<EOF
# Generated by \`npm run env:test\` — do not edit by hand.
# Local Supabase stack only. Integration tests refuse any non-local host
# (see tests/setup/int.ts).
NEXT_PUBLIC_SUPABASE_URL=$(read_key API_URL)
NEXT_PUBLIC_SUPABASE_ANON_KEY=$(read_key ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(read_key SERVICE_ROLE_KEY)
SUPABASE_DB_URL=$(read_key DB_URL)
NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3100
EOF

echo "Wrote .env.test.local from the running local stack."
