import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import DashboardRoute from '@/app/(business)/dashboard/page';
import DashboardAppointmentsRoute from '@/app/(business)/dashboard/appointments/page';
import DashboardServicesRoute from '@/app/(business)/dashboard/services/page';
import { LanguageProvider } from '@/lib/i18n/language-provider';
// Skipped: (business)/dashboard/** pages are typecheck-only placeholders (CLAUDE.md §8).
// Remove .skip once the real business dashboard is implemented.
describe.skip('business dashboard pages', () => { it('renders overview and filters detailed local appointments', async () => { const { unmount } = render(<LanguageProvider initialLocale="en">{await DashboardRoute()}</LanguageProvider>); expect(screen.getByText('Display-only revenue')).toBeInTheDocument(); expect(screen.getByRole('link', { name: /view all appointments/i })).toHaveAttribute('href', '/dashboard/appointments'); unmount(); render(<LanguageProvider initialLocale="en">{await DashboardAppointmentsRoute()}</LanguageProvider>); expect(screen.getByText('Yuval Erdrich')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Employee'), { target: { value: 'noa' } }); expect(screen.getAllByText('Noa Golan')).toHaveLength(3); expect(screen.queryByText('Yuval Erdrich')).not.toBeInTheDocument(); }); it('shows employee-linked services and keeps a new service local to the demo', async () => { render(<LanguageProvider initialLocale="en">{await DashboardServicesRoute()}</LanguageProvider>); expect(screen.getByRole('heading', { name: 'Service management' })).toBeInTheDocument(); expect(screen.getAllByText('Zohar Levi').length).toBeGreaterThan(0); fireEvent.click(screen.getByRole('button', { name: 'Add service' })); fireEvent.change(screen.getByLabelText('Employee'), { target: { value: 'noa' } }); fireEvent.change(screen.getByLabelText('Service name'), { target: { value: 'Demo blow dry' } }); fireEvent.change(screen.getByLabelText('Service description'), { target: { value: 'A local-only test service' } }); fireEvent.click(screen.getByRole('button', { name: 'Save in demo' })); expect(screen.getByText('Demo blow dry')).toBeInTheDocument(); expect(screen.getByText('Service updated in demo only')).toBeInTheDocument(); }); });
